export const NOTIFICATION_QUEUE_NAME = 'notification';

export const SNAPSHOT_QUEUE_NAME = 'snapshot';

export const NOTIFICATION = {
  NOTIFICATION_SAMPLE: 'NOTIFICATION_SAMPLE',

  NOTIFICATION_MAIL_REQUEST_LOGIN: 'NOTIFICATION_MAIL_REQUEST_LOGIN',

  NOTIFICATION_MAIL_CONFIRM_REGISTER: 'NOTIFICATION_MAIL_CONFIRM_REGISTER',

  NOTIFICATION_MAIL_INVITATION: 'NOTIFICATION_MAIL_INVITATION',
};
